background            #000000
foreground            #fae9cf

# black
color0  #000000
color8  #7c4d5a

# red
color1  #c7815e
color9  #df9571

# green
color2  #efb682
color10 #ffca97

# yellow
color3  #ffe2b6
color11 #ffe2ab

# blue
color4  #b95d4f
color12 #d17164

# magenta
color5  #e58f76
color13 #ffa489

#cyan
color6  #ffce91
color14 #ffe39a

#white
color7  #fae9cf
color15 #fff2eb
