# Background and foreground colors
background = #000000
foreground = #fae9cf

# Standard colors
palette = 0=#000000
palette = 1=#c7815e
palette = 2=#efb682
palette = 3=#ffe2b6
palette = 4=#b95d4f
palette = 5=#e58f76
palette = 6=#ffce91
palette = 7=#fae9cf

# Bright colors
palette = 8=#7c4d5a
palette = 9=#df9571
palette = 10=#ffca97
palette = 11=#ffe2ab
palette = 12=#d17164
palette = 13=#ffa489
palette = 14=#ffe39a
palette = 15=#fff2eb
