$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(229, 143, 118, 1)
$font_color = rgba(250, 233, 207, 1)
$placeholder_color = rgba(250, 233, 207, 0.7)
$check_color = rgba(255, 206, 145, 1)
